version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # We only want security updates + all the updates for the below packages
    # to lower the constant flow of PRs. But this means that occasionally
    # we need to check our dependencies for update manually!
    allow:
      # we want the latest root certs for security
      - dependency-name: "certifi"
      # it's our key library, we want it to be very up-to-date
      - dependency-name: "python-gitlab"
