queries:
  # we don't print any sensitive data by default and we are giving a loud warning about using
  # flags that enable such output
  - exclude: py/clear-text-logging-sensitive-data
  # we import functions for output using "from X import Y" to shorten these calls
  # to *improve* maintainability (see https://github.com/egnyte/gitlabform/pull/267)
  - exclude: py/import-and-import-from
