language: python

python:
- '3.5'
- '3.6'

services:
- docker

script:
- py.test

install:
- sudo apt-get -y install pandoc
- pip install pypandoc
- python setup.py develop
- docker build -t egnyte/gitlabform:$(cat version)-alpine3:9 -f alpine.Dockerfile .
- docker build -t egnyte/gitlabform:$(cat version)-debian9 -f alpine.Dockerfile .

deploy:
- provider: pypi
  user: python-egnyte
  password:
    secure: "DxUicAiXMUmoS0h5YYfGhcjeOvf5aPACN/ljn6GITR0MtoLFzRrmuuNPHuAseNbu8Q7fOcGVQ9ez6tQhGrjY0wzjSQmWIsSX9kez1OiVNrGDRKoKKLmfkxAO6mRU9GHOYT65mKQAW8Mdl14j9X1CxyO5qYb9CrmPCXCFQq8Bp45t1sTv1hypZpSJtrc5JUy8FymOFbI65nitr9wf3aWWMCS1Tv7JdpottiQ3OtmqYzvpRzbymDWcn2P8WX0nfrPTPaqJdt1wz+nzOusxj0SIO4LTPx0CjdALLNJqF9w9CZUvln93ZToIdwMLYPjWQ59WF7Mb42chTCABtLgetkl6qy9GFZtGauoeF9S3vnU7GT3lFVDTCVQeaAo5+nUvIbcj7NnBZipsEa+Cnv6Ijfrh4eEf7JMbnGuUl5rv6vxUl1t+uGMoWjDfHMPE9DvwzVg3AsPpyeu+olTY7xMDZ/47sR4/likTzeamGNL7cuj7BknkVSIH+wAbWpU9v5zctStNs3vPJX2gNdawsumsVZbAPm+6JeItt+bVWGcJEd6XfluNUFxj61YnYAi9QVj3L0lYPRRRa7LKP1ryDBwWeP4vUYdLhGj5qPTzN4HVJAN8bWGehaWK9f57DuuKvRw7V5vXkTRM5loRz0lziaWkUmew9sK3asw1jMC0uYsVak/us50="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
  before_deploy:
  - "pip install pypandoc"
- provider: script
  on:
    tags: true
  before_deploy:
  - docker tag egnyte/gitlabform:$(cat version)-alpine3:9 egnyte/gitlabform:latest-alpine3:9
  - docker tag egnyte/gitlabform:latest-alpine3:9 egnyte/gitlabform:latest
  - docker tag egnyte/gitlabform:$(cat version)-debian9 egnyte/gitlabform:latest-debian9
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
  - |
    for image in egnyte/gitlabform:$(cat version)-alpine3:9 egnyte/gitlabform:$(cat version)-debian9 egnyte/gitlabform:latest-alpine3:9 egnyte/gitlabform:latest-debian9 egnyte/gitlabform:latest
    do
      docker push $image
    done