language: python

jobs:
  include:
    # security tests
    - python: "3.7"
      env: SECURITY=true
    # integration tests
    - python: "3.7"
      env: INTEGRATION=true
    # unit tests + deployments (on tags only)
    - python: "3.7"
      env:
        - secure: "H6voGOBAqMavbLK63M3IAl+6GtAj1pZWExwPvmMytHVRXUeyxlC7Gy7piknUk+rAXE8F/bRwSRrdLxlN3i5SIQWlel4Zj+VSls8M7FUc05NtqSN8m3khm7Xr3u5/W58OXyiqJ3/9ozc5b8N4tuTPKBsxVlZCQuz1KhHn1WV/uPaJoKOlOoR3S6jJFPCPpDYNaadBtZNrmRgXux3KProO6pikqHQ6W9qtvK2YjJXVfXF3R1hhfdWD5Jo6yX0B1aINYWYoUWiQXdaahp0iU7ALENeaij6mB+U1Fo6/Fu9xHvU4cBdRsh2WtZUjHjiIKh5ZYFtWurQr8l/7fNz+zsaCD4y2Uc3QNvLsZ2H57sh593luT8UbQWrwUVnRkO2f5plGY/4M9M3YpeleUNbp9MX6PJHafl7YYtGIGwdad3l70d0Qmf1VxT2nSHp3VvmlxAWGtKBbMtKWYBaUZOjnteGCYfE5SosD54gmgb2gkspRafI+ef+A6MK5+WU8SAmCtxrzJgky9GsuRhn9KddOx1EZqPMfVaByy6Tcjp/f2Uc66Rd416IPjLEEcU6XmO8gGV9Obu5VEbvdiHxEnJTHcXmrB4fqjntn60Yn/1R9P0U5QVBqJowf6zTOztRtD9JgYaWYpz0/TMvkasLFXdvhCJl2vCIp91cY2Pr/Z/RzVce7eh4="
        - alpine_version=alpine3.10 debian_version=buster
    # unit tests only
    - python: "3.8"
    - python: "3.6"
    - python: "3.5"

services:
- docker

addons:
  apt:
    packages:
      - expect-dev  # for unbuffer

install:
- sudo apt-get -y install pandoc
- pip install pypandoc
- python setup.py develop

before_script:
- if [[ -n $INTEGRATION ]] ; then bash run_gitlab_in_docker.sh ; fi
- if [[ -n $INTEGRATION ]] ; then export GITLAB_URL=$(cat gitlab_url.txt) ; fi
- if [[ -n $INTEGRATION ]] ; then export GITLAB_TOKEN=$(cat gitlab_token.txt) ; fi
- if [[ -n $SECURITY ]] ; then pip install bandit ; fi

script:
# unit tests
- if [[ -z $INTEGRATION ]] ; then unbuffer py.test --ignore gitlabform/gitlabform/test ; fi
# integration tests
- if [[ -n $INTEGRATION ]] ; then unbuffer py.test gitlabform/gitlabform/test ; fi
# security tests
- if [[ -n $SECURITY ]] ; then bandit -r gitlabform -x "*/test/*" ; fi

deploy:
- provider: pypi
  user: python-egnyte
  password:
    secure: "DxUicAiXMUmoS0h5YYfGhcjeOvf5aPACN/ljn6GITR0MtoLFzRrmuuNPHuAseNbu8Q7fOcGVQ9ez6tQhGrjY0wzjSQmWIsSX9kez1OiVNrGDRKoKKLmfkxAO6mRU9GHOYT65mKQAW8Mdl14j9X1CxyO5qYb9CrmPCXCFQq8Bp45t1sTv1hypZpSJtrc5JUy8FymOFbI65nitr9wf3aWWMCS1Tv7JdpottiQ3OtmqYzvpRzbymDWcn2P8WX0nfrPTPaqJdt1wz+nzOusxj0SIO4LTPx0CjdALLNJqF9w9CZUvln93ZToIdwMLYPjWQ59WF7Mb42chTCABtLgetkl6qy9GFZtGauoeF9S3vnU7GT3lFVDTCVQeaAo5+nUvIbcj7NnBZipsEa+Cnv6Ijfrh4eEf7JMbnGuUl5rv6vxUl1t+uGMoWjDfHMPE9DvwzVg3AsPpyeu+olTY7xMDZ/47sR4/likTzeamGNL7cuj7BknkVSIH+wAbWpU9v5zctStNs3vPJX2gNdawsumsVZbAPm+6JeItt+bVWGcJEd6XfluNUFxj61YnYAi9QVj3L0lYPRRRa7LKP1ryDBwWeP4vUYdLhGj5qPTzN4HVJAN8bWGehaWK9f57DuuKvRw7V5vXkTRM5loRz0lziaWkUmew9sK3asw1jMC0uYsVak/us50="
  distributions: "sdist bdist_wheel"
  on:
    repo: egnyte/gitlabform
    tags: true
    python: "3.7"
  before_deploy:
  - "pip install pypandoc"

- provider: script
  on:
    repo: egnyte/gitlabform
    tags: true
    python: "3.7"
  before_deploy:
  - bash build_docker_images.sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script: PUSH_IMAGES=true bash build_docker_images.sh
