name: Main branch

on:
  push:
    branches:
      - main

jobs:

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install -e .[docs]
      - name: Build docs
        run: |
          mkdocs build

  linters:
    uses: ./.github/workflows/linters.yml

  tests-standard:
    uses: ./.github/workflows/tests-standard.yml

  tests-premium:
    uses: ./.github/workflows/tests-premium.yml

  tests-ultimate:
    uses: ./.github/workflows/tests-ultimate.yml