name: Tests (acceptance)

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pytest==6.1.1 xkcdpass==1.17.6
          python setup.py develop
      - name: Run acceptance tests
        env:
          GITLAB_EE_LICENSE: ${{ secrets.GITLAB_EE_LICENSE }}
        run: |
          ./dev/run_gitlab_in_docker.sh
          py.test gitlabform/gitlabform/test/test_archive_project.py
          py.test gitlabform/gitlabform/test/test_branches.py
          py.test gitlabform/gitlabform/test/test_deploy_keys.py
          py.test gitlabform/gitlabform/test/test_files.py
