---
name: Publish 🐙🐱 to GitHub

on:
  push:
    tags:
      - 'v*'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Create release in GitHub
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref }}
          body: "(this is a placeholder, it will be replaced with a changelog contents)"
          # This token is provided by Actions, you do not need to create your own token
          token: ${{ secrets.GITHUB_TOKEN }}
