---
name: Publish 🐍 to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Build
        run: |
          pip install wheel
          python setup.py build sdist bdist_wheel
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Create release in GitHub
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref }}
          body: "(this is a placeholder, it will be replaced with a changelog contents)"
          # This token is provided by Actions, you do not need to create your own token
          token: ${{ secrets.GITHUB_TOKEN }}
