---
name: Publish 🐳 to DockerHub

on:
  push:
    tags:
      - "v*"

env:
  alpine_version: alpine3.12
  debian_version: buster

jobs:
  build-n-publish:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [alpine, debian]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install packaging
      - name: Publish to DockerHub
        env:
          os: ${{ matrix.os }}
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          release_type=$(dev/check_release_type.py)
          export release_type
          ./dev/build_docker_images.sh
