---
name: Publish 🐳 to DockerHub

on:
  push:
    tags:
      - 'v*'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install wheel
          pip install packaging
      - name: Get the version from the tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Wait for PyPI release
        run: |
          pip download gitlabform==${{ env.VERSION }} > /dev/null
          while [ $? -ne 0 ]; do sleep 10; pip3 download gitlabform==${{ env.VERSION }} > /dev/null ; done
        shell: bash {0}
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/gitlabform/gitlabform
          flavor: |
            latest=auto
          tags: |
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern={{major}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # gitlabform/gitlabform image is going to be here
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          # This token is provided by Actions, you do not need to create your own token
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish image to registries
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./dev/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
